pull_request_rules:
  - name: automatic merge
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
      - label=merge
    actions:
      merge:
        method: rebase
        strict: true
  - name: Auto merge MickeyMoz
    conditions:
      - author=MickeyMoz
      - base=master
    actions:
      merge:
        method: rebase
        strict: true
